### ISSUE TITLE
iso:thes:superodinate niet meer beschikbaar in getty

### ISSUE THREAD

**Issue by dieuska** [OnroerendErfgoed/skosprovider_getty#17]
volgens mij bestaan er geen superordinates meer in de getty data:
http://vocab.getty.edu/resource/iso-thes/superOrdinate?role=all
Bovenstaande link geeft alle triples die dit gebruiken, en dit zijn enkel triples die 'superordinate' op zich beschrijven.
'superordinate' wordt dus nergens gebruikt om hun subjects te beschrijven
-->Tests op superordinate is momenteel uitgeschakeld met '@pytest.mark.xfail'

**Comment by koenedaele** [comment]
Is it possible to simulate this with a SPARQL query? "Give me all concepts that have this collection as a iso:subOrdinateArray"

**Comment by dieuska** [comment]
Hey,

met onderstaande SPARQL kan je al zien dat de superOrdinate nergens gebruikt wordt als predicate in de Getty-triplestore:
PREFIX iso-thes: <http://purl.org/iso25964/skos-thes#>
select * {?s iso-thes:superOrdinate ?o} LIMIT 100

subOrdinateArrays daarentegen worden wel gebruikt als predicate
PREFIX iso-thes: <http://purl.org/iso25964/skos-thes#>
select * {?s iso-thes:subordinateArray ?o} LIMIT 100

SPARQL queries kan je hier uitvoeren:
http://vocab.getty.edu/sparql

**Comment by dieuska** [comment]
Onderstaande query geeft de subject( Concept) terug dat als subordinate een bepaalde collection geeft:
PREFIX aat: <http://vocab.getty.edu/aat/>
PREFIX iso-thes: <http://purl.org/iso25964/skos-thes#>
SELECT * WHERE {?s iso-thes:subordinateArray aat:300138225-array}

Dit principe kunnen we dus hopelijk gebruiken om de superordinates aan te vullen
